version: '3.4'

services:
  ttcms.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MvcClient=http://docker.for.win.localhost:5100              #Local: You need to open your local dev-machine firewall at range 5100-5110. 
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5105:80"


  ttcms.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5103:80"


  ttcms.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5101:80"



  ttcms.webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CatalogUrl=http://ttcms.catalog.api
      - IdentityUrl=http://docker.for.win.localhost:5105
      - PurchaseUrl=http://ttcms.basket.api
      - CallBackUrl=http://docker.for.win.localhost:5100
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - UseLoadTest=${USE_LOADTEST:-False}
      
    ports:
      - "5100:80"

